# Generated by Django 3.0 on 2020-01-13 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_traffic', '0003_auto_20200113_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingentry',
            name='no_places',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Anzahl Parkplätze'),
            preserve_default=False,
        ),
    ]
