# Generated by Django 3.0 on 2020-01-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_traffic', '0004_parkingentry_no_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghoursparkingentry',
            name='parking_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_traffic.ParkingEntry'),
        ),
    ]
