# Generated by Django 3.0 on 2020-01-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_nature', '0002_openinghoursviewpointentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghoursviewpointentry',
            options={'verbose_name': 'Öffnungszeit', 'verbose_name_plural': 'Öffnungszeiten'},
        ),
    ]
