# Generated by Django 3.0 on 2020-01-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_nature', '0004_addressviewpointentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressviewpointentry',
            options={'verbose_name_plural': 'Adresse'},
        ),
    ]
