# Generated by Django 3.0 on 2020-01-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_nature', '0005_auto_20200129_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressviewpointentry',
            name='viewpoint_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_nature.ViewpointEntry'),
        ),
        migrations.AlterField(
            model_name='openinghoursviewpointentry',
            name='viewpoint_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_nature.ViewpointEntry'),
        ),
    ]
