# Generated by Django 3.0 on 2019-12-23 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geomodels', '0008_auto_20191223_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundvalueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Titel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('price', models.TextField(verbose_name='Preis')),
                ('id_subcategory', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='geomodels.Subcategory', verbose_name='Unterkategorie')),
            ],
            options={
                'verbose_name': 'Bodenrichtwert',
                'verbose_name_plural': 'Bodenrichtwerte',
            },
        ),
        migrations.CreateModel(
            name='BuildingareaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Titel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('areanumber', models.IntegerField(verbose_name='Baugebietnummer')),
                ('id_subcategory', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='geomodels.Subcategory', verbose_name='Unterkategorie')),
            ],
            options={
                'verbose_name': 'Baugebiet',
                'verbose_name_plural': 'Baugebiete',
            },
        ),
    ]
