# Generated by Django 3.0 on 2020-01-13 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0012_address'),
        ('category_living', '0003_auto_20191231_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingareaentry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='buildingareaentry',
            name='no_buildingplaces',
            field=models.IntegerField(default=1, verbose_name='Anzahl Bauplätze'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingareaentry',
            name='no_free_buildingplaces',
            field=models.IntegerField(default=1, verbose_name='Anzahl freie Bauplätze'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundvalueentry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='groundvalueentry',
            name='using_type',
            field=models.CharField(choices=[('private', 'privat'), ('mixed', 'gemischt genutzt'), ('commercial', 'gewerblich')], default='private', max_length=30, verbose_name='Nutzungsart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playgroundentry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='schoolentry',
            name='school_type',
            field=models.CharField(choices=[('1', 'Grundschule'), ('2', 'Hauptschule'), ('3', 'Realschule'), ('4', 'Gesamtschule'), ('5', 'Gymnasium')], default=1, max_length=30, verbose_name='Schulart'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AddressSchoolEntry',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geomodels.Address')),
                ('school_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_living.SchoolEntry')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
            bases=('geomodels.address',),
        ),
        migrations.CreateModel(
            name='AddressPlaygroundEntry',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geomodels.Address')),
                ('playground_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_living.PlaygroundEntry')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
            bases=('geomodels.address',),
        ),
    ]
