# Generated by Django 3.0 on 2020-01-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_living', '0004_auto_20200113_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundvalueentry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis (€) pro m²'),
        ),
    ]
