# Generated by Django 3.0 on 2020-01-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_living', '0005_auto_20200114_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundvalueentry',
            name='using_type',
            field=models.CharField(choices=[('privat', 'privat'), ('gemischt genutzt', 'gemischt genutzt'), ('gewerblich', 'gewerblich')], max_length=30, verbose_name='Nutzungsart'),
        ),
    ]
