# Generated by Django 3.0 on 2020-01-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_living', '0006_auto_20200114_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolentry',
            name='school_type',
            field=models.CharField(choices=[('Grundschule', 'Grundschule'), ('Hauptschule', 'Hauptschule'), ('Realschule', 'Realschule'), ('Gesamtschule', 'Gesamtschule'), ('Gymnasium', 'Gymnasium')], max_length=30, verbose_name='Schulart'),
        ),
    ]
