# Generated by Django 3.0 on 2020-01-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_living', '0007_auto_20200114_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressplaygroundentry',
            options={'verbose_name_plural': 'Adresse'},
        ),
        migrations.AlterModelOptions(
            name='addressschoolentry',
            options={'verbose_name_plural': 'Adresse'},
        ),
    ]
