# Generated by Django 3.0 on 2020-01-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_living', '0008_auto_20200129_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressplaygroundentry',
            name='playground_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_living.PlaygroundEntry'),
        ),
        migrations.AlterField(
            model_name='addressschoolentry',
            name='school_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_living.SchoolEntry'),
        ),
    ]
