# Generated by Django 3.0 on 2020-01-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0011_openinghours'),
        ('category_tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHoursMonumentEntry',
            fields=[
                ('openinghours_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geomodels.OpeningHours')),
                ('monument_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_tourism.MonumentEntry')),
            ],
            bases=('geomodels.openinghours',),
        ),
        migrations.CreateModel(
            name='OpeningHoursChurchEntry',
            fields=[
                ('openinghours_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geomodels.OpeningHours')),
                ('church_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_tourism.ChurchEntry')),
            ],
            bases=('geomodels.openinghours',),
        ),
    ]
