# Generated by Django 3.0 on 2020-01-13 21:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0012_address'),
        ('category_tourism', '0003_auto_20200113_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationentry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='churchentry',
            name='buildingyear',
            field=models.PositiveIntegerField(default=1900, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Baujahr'),
        ),
        migrations.AddField(
            model_name='churchentry',
            name='denomination',
            field=models.CharField(choices=[('1', 'evangelisch'), ('2', 'katholisch'), ('3', 'sonstiges')], default=1, max_length=30, verbose_name='Konfession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monumententry',
            name='buildingyear',
            field=models.PositiveIntegerField(default=1900, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Errichtungsjahr'),
        ),
        migrations.AddField(
            model_name='monumententry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='trailentry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='trailentry',
            name='difficulty',
            field=models.CharField(choices=[('1', 'leicht'), ('2', 'mittel'), ('3', 'schwer')], default=1, max_length=30, verbose_name='Schwierigkeitsgrad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailentry',
            name='length',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Länge (km)'),
        ),
        migrations.CreateModel(
            name='AddressTrailEntry',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geomodels.Address')),
                ('trail_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_tourism.TrailEntry')),
            ],
            options={
                'verbose_name': 'Startadresse',
                'verbose_name_plural': 'Startadressen',
            },
            bases=('geomodels.address',),
        ),
        migrations.CreateModel(
            name='AddressMonumentEntry',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geomodels.Address')),
                ('monument_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_tourism.MonumentEntry')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
            bases=('geomodels.address',),
        ),
        migrations.CreateModel(
            name='AddressChurchEntry',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geomodels.Address')),
                ('church_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_tourism.ChurchEntry')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
            bases=('geomodels.address',),
        ),
        migrations.CreateModel(
            name='AddressAccommodationEntry',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geomodels.Address')),
                ('accommodation_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_tourism.AccommodationEntry')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
            bases=('geomodels.address',),
        ),
    ]
