# Generated by Django 3.0 on 2020-01-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_tourism', '0006_auto_20200129_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressaccommodationentry',
            name='accommodation_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_tourism.AccommodationEntry'),
        ),
        migrations.AlterField(
            model_name='addresschurchentry',
            name='church_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_tourism.ChurchEntry'),
        ),
        migrations.AlterField(
            model_name='addressmonumententry',
            name='monument_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_tourism.MonumentEntry'),
        ),
        migrations.AlterField(
            model_name='addresstrailentry',
            name='trail_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_tourism.TrailEntry'),
        ),
        migrations.AlterField(
            model_name='openinghourschurchentry',
            name='church_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_tourism.ChurchEntry'),
        ),
        migrations.AlterField(
            model_name='openinghoursmonumententry',
            name='monument_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_tourism.MonumentEntry'),
        ),
    ]
