# Generated by Django 3.0 on 2020-01-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0011_openinghours'),
        ('category_sparetime', '0002_openinghourssportcentreentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningHoursSportcentreEntry',
            new_name='OpeningHoursSportscentreEntry',
        ),
        migrations.RenameField(
            model_name='openinghourssportscentreentry',
            old_name='sportcentre_entry',
            new_name='sportscentre_entry',
        ),
    ]
