# Generated by Django 3.0 on 2020-01-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_sparetime', '0003_auto_20200113_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghourssportscentreentry',
            options={'verbose_name': 'Öffnungszeit', 'verbose_name_plural': 'Öffnungszeiten'},
        ),
    ]
