# Generated by Django 3.0 on 2020-01-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_sparetime', '0005_addresssportscentreentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresssportscentreentry',
            options={'verbose_name_plural': 'Adresse'},
        ),
    ]
