# Generated by Django 3.0 on 2020-01-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_sparetime', '0006_auto_20200129_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresssportscentreentry',
            name='sportscentre_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_sparetime.SportscentreEntry'),
        ),
        migrations.AlterField(
            model_name='openinghourssportscentreentry',
            name='sportscentre_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_sparetime.SportscentreEntry'),
        ),
    ]
