# Generated by Django 3.0 on 2019-12-12 16:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=1024)),
                ('description', models.TextField(db_column='desciption')),
                ('image', models.ImageField(db_column='image', upload_to='images/category/')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['title'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=1024)),
                ('description', models.TextField(db_column='description')),
                ('type', models.IntegerField()),
                ('image', models.ImageField(db_column='image', upload_to='images/subcategory/')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomodels.Category')),
            ],
            options={
                'db_table': 'subcategory',
                'ordering': ['title'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=1024)),
                ('content', models.TextField(db_column='content')),
                ('coordinates', django.contrib.postgres.fields.jsonb.JSONField()),
                ('id_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomodels.Subcategory')),
            ],
            options={
                'db_table': 'entry',
                'ordering': ['title'],
                'managed': True,
            },
        ),
    ]
