# Generated by Django 3.0 on 2019-12-18 09:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0002_auto_20191218_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='images/category/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Koordinaten'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geomodels.Subcategory', verbose_name='Unterkategorie'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geomodels.Category', verbose_name='Hauptkategorie'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(upload_to='images/subcategory/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.CharField(choices=[('point', 'Punkt'), ('polygon', 'Polygon'), ('static', 'Statisch')], max_length=20, verbose_name='Typ der Kategorie'),
        ),
    ]
