# Generated by Django 3.0 on 2019-12-19 23:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0003_auto_20191218_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryTrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Titel')),
                ('content', models.TextField(null=True, verbose_name='Inhalt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Batterien-Müll-Punkt',
                'verbose_name_plural': 'Batterien-Müll-Punkte',
            },
        ),
        migrations.CreateModel(
            name='ClothingTrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Titel')),
                ('content', models.TextField(null=True, verbose_name='Inhalt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Kleidungs-Müll-Punkt',
                'verbose_name_plural': 'Kleidungs-Müll-Punkte',
            },
        ),
        migrations.CreateModel(
            name='GlassTrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Titel')),
                ('content', models.TextField(null=True, verbose_name='Inhalt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Glass-Müll-Punkt',
                'verbose_name_plural': 'Glass-Müll-Punkte',
            },
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='type',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AddField(
            model_name='glasstrash',
            name='id_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geomodels.Subcategory', verbose_name='Unterkategorie'),
        ),
        migrations.AddField(
            model_name='clothingtrash',
            name='id_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geomodels.Subcategory', verbose_name='Unterkategorie'),
        ),
        migrations.AddField(
            model_name='batterytrash',
            name='id_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geomodels.Subcategory', verbose_name='Unterkategorie'),
        ),
    ]
