# Generated by Django 3.0 on 2019-12-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0005_auto_20191222_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClothingTrash',
            new_name='BatteryTrashEntry',
        ),
        migrations.RenameModel(
            old_name='BatteryTrash',
            new_name='ClothingTrashEntry',
        ),
        migrations.AlterModelOptions(
            name='batterytrashentry',
            options={'verbose_name': 'Batterien-Müll-Punkt', 'verbose_name_plural': 'Batterien-Müll-Punkte'},
        ),
        migrations.AlterModelOptions(
            name='clothingtrashentry',
            options={'verbose_name': 'Kleidungs-Müll-Punkt', 'verbose_name_plural': 'Kleidungs-Müll-Punkte'},
        ),
    ]
