# Generated by Django 3.0 on 2019-12-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0006_auto_20191222_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glasstrashentry',
            options={'verbose_name': 'Glas-Müll-Punkt', 'verbose_name_plural': 'Glas-Müll-Punkte'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='entry_types',
            field=models.CharField(choices=[('glasstrash', 'Glasmüll-Abgabestellen'), ('clothing', 'Altkleider-Abgabestellen'), ('batterytrash', 'Altbatterien-Abgabestellen')], default='glasstrash', max_length=30, verbose_name='Art der möglichen Einträge'),
        ),
    ]
