# Generated by Django 3.0 on 2019-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0007_auto_20191222_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingtrashentry',
            name='id_subcategory',
        ),
        migrations.RemoveField(
            model_name='glasstrashentry',
            name='id_subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='coordinates_type',
            field=models.CharField(choices=[('point', 'Punkt'), ('polygon', 'Polygon')], default='point', max_length=30, verbose_name='Art der Koordinaten der Einträge'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='entry_types',
            field=models.CharField(choices=[('glasstrash', 'Glasmüll-Abgabestellen'), ('clothingtrash', 'Altkleider-Abgabestellen'), ('groundvalueliving', 'Bodenrichtwerte'), ('buildingarealiving', 'Baugebiete')], default='glasstrash', max_length=30, verbose_name='Art der möglichen Einträge'),
        ),
        migrations.DeleteModel(
            name='BatteryTrashEntry',
        ),
        migrations.DeleteModel(
            name='ClothingTrashEntry',
        ),
        migrations.DeleteModel(
            name='GlassTrashEntry',
        ),
    ]
