# Generated by Django 3.0 on 2019-12-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0008_auto_20191223_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='entry_types',
            field=models.CharField(choices=[('groundvalueliving', 'Bodenrichtwerte'), ('buildingarealiving', 'Baugebiete'), ('playgroundliving', 'Spielplätze'), ('schoolliving', 'Schulen'), ('viewpointnature', 'Aussichtspunkte'), ('sportscentresparetime', 'Sporthallen'), ('monumenttourism', 'Denkmäler'), ('trailtourism', 'Wanderwege'), ('churchtourism', 'Kirchen'), ('accommodationtourism', 'Unterkünfte'), ('parkingtraffic', 'Parkplätze'), ('glasstrash', 'Glasmüll-Abgabestellen'), ('clothingtrash', 'Altkleider-Abgabestellen'), ('batterytrash', 'Batterie-Abgabestellen'), ('illuminanttrash', 'Leuchtmittel-Abgabestellen'), ('electrotrash', 'Elektroschrott-Abgabestellen'), ('recyclingcentretrash', 'Recyclingcenter')], default='glasstrash', max_length=30, verbose_name='Art der möglichen Einträge'),
        ),
    ]
