# Generated by Django 3.0 on 2020-01-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0009_auto_20191223_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorie (category)', 'verbose_name_plural': 'Kategorien (categories)'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Unterkategorie (feature class)', 'verbose_name_plural': 'Unterkategorien (feature classes)'},
        ),
    ]
