# Generated by Django 3.0 on 2020-01-13 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0011_openinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=1024, verbose_name='Straße')),
                ('housenumber', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Hausnummer')),
                ('zipcode', models.PositiveIntegerField(default=74821, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='PLZ')),
                ('city', models.CharField(default='Mosbach', max_length=1024, verbose_name='Ort')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
        ),
    ]
