# Generated by Django 3.0 on 2020-01-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomodels', '0012_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adresse'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorie (layer group)', 'verbose_name_plural': 'Kategorien (layer groups)'},
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name': 'Öffnungszeit'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Unterkategorie (layer)', 'verbose_name_plural': 'Unterkategorien (layers)'},
        ),
    ]
