# Generated by Django 3.0 on 2019-12-23 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geomodels', '0008_auto_20191223_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Titel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('openingHours', models.TextField(verbose_name='Öffnungszeiten')),
                ('id_subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='geomodels.Subcategory', verbose_name='Unterkategorie')),
            ],
            options={
                'verbose_name': 'Glassammelstelle',
                'verbose_name_plural': 'Glassammelstellen',
            },
        ),
        migrations.CreateModel(
            name='ClothingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Titel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('openingHours', models.TextField(verbose_name='Öffnungszeiten')),
                ('id_subcategory', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='geomodels.Subcategory', verbose_name='Unterkategorie')),
            ],
            options={
                'verbose_name': 'Altkleidersammelstelle',
                'verbose_name_plural': 'Altkleidersammelstelle',
            },
        ),
    ]
