# Generated by Django 3.0 on 2020-01-08 10:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_trash', '0002_auto_20191223_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glassentry',
            name='openingHours',
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Montag'), size=None)),
                ('tuesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Dienstag'), size=None)),
                ('wednesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Mittwoch'), size=None)),
                ('thursday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Donnerstag'), size=None)),
                ('friday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Freitag'), size=None)),
                ('saturday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Samstag'), size=None)),
                ('sunday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Sonntag'), size=None)),
                ('glass_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_trash.GlassEntry', verbose_name='Glasssammelstelle')),
            ],
            options={
                'verbose_name': 'Öffnungszeit',
                'verbose_name_plural': 'Öffnungszeiten',
            },
        ),
    ]
