# Generated by Django 3.0 on 2020-01-08 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_trash', '0003_auto_20200108_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='friday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Freitag'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='monday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Montag'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='saturday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Samstag'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='sunday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Sonntag'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='thursday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Donnerstag'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='tuesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Dienstag'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='wednesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Mittwoch'), blank=True, null=True, size=None),
        ),
    ]
