# Generated by Django 3.0 on 2020-01-12 13:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_trash', '0004_auto_20200108_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHoursBatteryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Montag'), blank=True, null=True, size=None)),
                ('tuesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Dienstag'), blank=True, null=True, size=None)),
                ('wednesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Mittwoch'), blank=True, null=True, size=None)),
                ('thursday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Donnerstag'), blank=True, null=True, size=None)),
                ('friday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Freitag'), blank=True, null=True, size=None)),
                ('saturday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Samstag'), blank=True, null=True, size=None)),
                ('sunday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Sonntag'), blank=True, null=True, size=None)),
                ('battery_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_trash.BatteryEntry')),
            ],
            options={
                'verbose_name': 'Öffnungszeit',
                'verbose_name_plural': 'Öffnungszeiten',
            },
        ),
        migrations.CreateModel(
            name='OpeningHoursClothingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Montag'), blank=True, null=True, size=None)),
                ('tuesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Dienstag'), blank=True, null=True, size=None)),
                ('wednesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Mittwoch'), blank=True, null=True, size=None)),
                ('thursday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Donnerstag'), blank=True, null=True, size=None)),
                ('friday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Freitag'), blank=True, null=True, size=None)),
                ('saturday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Samstag'), blank=True, null=True, size=None)),
                ('sunday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Sonntag'), blank=True, null=True, size=None)),
                ('clothing_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_trash.ClothingEntry')),
            ],
            options={
                'verbose_name': 'Öffnungszeit',
                'verbose_name_plural': 'Öffnungszeiten',
            },
        ),
        migrations.CreateModel(
            name='OpeningHoursElectroEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Montag'), blank=True, null=True, size=None)),
                ('tuesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Dienstag'), blank=True, null=True, size=None)),
                ('wednesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Mittwoch'), blank=True, null=True, size=None)),
                ('thursday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Donnerstag'), blank=True, null=True, size=None)),
                ('friday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Freitag'), blank=True, null=True, size=None)),
                ('saturday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Samstag'), blank=True, null=True, size=None)),
                ('sunday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Sonntag'), blank=True, null=True, size=None)),
                ('electro_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_trash.ElectroEntry')),
            ],
            options={
                'verbose_name': 'Öffnungszeit',
                'verbose_name_plural': 'Öffnungszeiten',
            },
        ),
        migrations.CreateModel(
            name='OpeningHoursGlassEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Montag'), blank=True, null=True, size=None)),
                ('tuesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Dienstag'), blank=True, null=True, size=None)),
                ('wednesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Mittwoch'), blank=True, null=True, size=None)),
                ('thursday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Donnerstag'), blank=True, null=True, size=None)),
                ('friday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Freitag'), blank=True, null=True, size=None)),
                ('saturday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Samstag'), blank=True, null=True, size=None)),
                ('sunday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Sonntag'), blank=True, null=True, size=None)),
                ('glass_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_trash.GlassEntry')),
            ],
            options={
                'verbose_name': 'Öffnungszeit',
                'verbose_name_plural': 'Öffnungszeiten',
            },
        ),
        migrations.CreateModel(
            name='OpeningHoursIlluminantEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Montag'), blank=True, null=True, size=None)),
                ('tuesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Dienstag'), blank=True, null=True, size=None)),
                ('wednesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Mittwoch'), blank=True, null=True, size=None)),
                ('thursday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Donnerstag'), blank=True, null=True, size=None)),
                ('friday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Freitag'), blank=True, null=True, size=None)),
                ('saturday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Samstag'), blank=True, null=True, size=None)),
                ('sunday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Sonntag'), blank=True, null=True, size=None)),
                ('illuminant_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_trash.IlluminantEntry')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHoursRecyclingcentreEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Montag'), blank=True, null=True, size=None)),
                ('tuesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Dienstag'), blank=True, null=True, size=None)),
                ('wednesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Mittwoch'), blank=True, null=True, size=None)),
                ('thursday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Donnerstag'), blank=True, null=True, size=None)),
                ('friday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Freitag'), blank=True, null=True, size=None)),
                ('saturday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Samstag'), blank=True, null=True, size=None)),
                ('sunday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Sonntag'), blank=True, null=True, size=None)),
                ('recyclingcentre_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_trash.RecyclingcentreEntry')),
            ],
            options={
                'verbose_name': 'Öffnungszeit',
                'verbose_name_plural': 'Öffnungszeiten',
            },
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
