# Generated by Django 3.0 on 2020-01-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_trash', '0006_auto_20200113_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghoursbatteryentry',
            options={'verbose_name': 'Öffnungszeit', 'verbose_name_plural': 'Öffnungszeiten'},
        ),
        migrations.AlterModelOptions(
            name='openinghoursclothingentry',
            options={'verbose_name': 'Öffnungszeit', 'verbose_name_plural': 'Öffnungszeiten'},
        ),
        migrations.AlterModelOptions(
            name='openinghourselectroentry',
            options={'verbose_name': 'Öffnungszeit', 'verbose_name_plural': 'Öffnungszeiten'},
        ),
        migrations.AlterModelOptions(
            name='openinghoursglassentry',
            options={'verbose_name': 'Öffnungszeit', 'verbose_name_plural': 'Öffnungszeiten'},
        ),
        migrations.AlterModelOptions(
            name='openinghoursilluminantentry',
            options={'verbose_name': 'Öffnungszeit', 'verbose_name_plural': 'Öffnungszeiten'},
        ),
        migrations.AlterModelOptions(
            name='openinghoursrecyclingcentreentry',
            options={'verbose_name': 'Öffnungszeit', 'verbose_name_plural': 'Öffnungszeiten'},
        ),
    ]
