# Generated by Django 3.0 on 2020-01-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_trash', '0008_auto_20200113_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressglassentry',
            options={'verbose_name': 'Adresse'},
        ),
        migrations.AlterModelOptions(
            name='openinghoursglassentry',
            options={'verbose_name': 'Öffnungszeit'},
        ),
    ]
